"""New Review.test_url

Revision ID: 30e48e4dd2c9
Revises: 340812507e2e
Create Date: 2015-10-16 10:59:14.781471

"""

# revision identifiers, used by Alembic.
revision = '30e48e4dd2c9'
down_revision = '340812507e2e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("review") as batch_op:
        batch_op.add_column(sa.Column('test_url', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("review") as batch_op:
        batch_op.drop_column('test_url')
    ### end Alembic commands ###
