"""track last syncd

Revision ID: 3dff2445d764
Revises: None
Create Date: 2014-09-02 19:57:10.268323

"""

# revision identifiers, used by Alembic.
revision = '3dff2445d764'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('syncd', sa.DateTime(timezone=True), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('review', 'syncd')
    ### end Alembic commands ###
