"""Track who initiated a test

Revision ID: 52ea8ea11fb7
Revises: 46ce46fd2207
Create Date: 2014-09-21 13:07:17.919523

"""

# revision identifiers, used by Alembic.
revision = '52ea8ea11fb7'
down_revision = '46ce46fd2207'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'review_test', sa.Column('requester_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'review_test', 'requester_id')
    ### end Alembic commands ###
