"""tracking locks

Revision ID: 196c607d7498
Revises: 2bfe54c360dc
Create Date: 2014-09-08 13:19:38.145113

"""

# revision identifiers, used by Alembic.
revision = '196c607d7498'
down_revision = '2bfe54c360dc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('lock_id', sa.Integer(), nullable=True))
    op.add_column('review', sa.Column('locked', sa.DateTime(timezone=True), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('review', 'locked')
    op.drop_column('review', 'lock_id')
    ### end Alembic commands ###
