"""active series

Revision ID: 4308d0cfc691
Revises: 3dff2445d764
Create Date: 2014-09-02 21:00:38.925950

"""

# revision identifiers, used by Alembic.
revision = '4308d0cfc691'
down_revision = '3dff2445d764'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('series', sa.Column('active', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('series', 'active')
    ### end Alembic commands ###
